image: docker

default:
  tags: 
    - be-runner

stages:
  - init 
  - test        
  - build
  # - deploy

init:
  stage: init
  script:
    - sudo docker-compose up -d --build

test:
  stage: test
  script:
    - CGO_ENABLED=0 go test ./... -coverprofile=coverage-report.out
    - go tool cover -html=coverage-report.out -o coverage-report.html
    - go tool cover -func=coverage-report.out
  artifacts:
    paths:
      - coverage-report.html
    expire_in: 1 hour
  coverage: "/\\(statements\\)\\s+\\d+.?\\d+%/"

build-job:       
  stage: build
  when: on_success
  only: 
    - main
  image: docker:stable

  services:
      - name: docker:dind
        command: ["--tls=false"]

  script:
      - docker login gitlab.informatika.org:4567 -u access-token-sm-be -p $CI_TOKEN
      - docker build -t gitlab.informatika.org:4567/if3250_2024_k03_02_sm-02/sm-be .
      - docker push gitlab.informatika.org:4567/if3250_2024_k03_02_sm-02/sm-be

