version: '3'

services:
  backend:
    container_name: backend
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres-db
    volumes:
      - .:/app

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    env_file:
      - ../.env
    ports:
      - 5433:5432
    environment:
      POSTGRES_ROOT_PASSWORD: $POSTGRES_ROOT_PASSWORD
      POSTGRES_DATABASE: $POSTGRES_DATABASE
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - postgres-data:/variable/lib/postgresql/data
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql

volumes:
  postgres-data:
    driver: local